version: '3.8'
services:
################################
# Webapp
################################

################################
# API's
################################

  wildzone-api-suppliers:
      image: jjuless/wildzone-api-suppliers
      environment:
        DB_HOST: wildzone-database-suppliers
        DB_USER: $DB_USER
        DB_PASSWORD: $DB_PASSWORD
        DB_DATABASE: $DB_DATABASE
        DB_PORT: $DB_PORT
        DB_DIALECT: $DB_DIALECT
      ports:
        - 3002:3000
      restart: on-failure

  wildzone-api-products:
    image: jjuless/wildzone-api-products
    ports:
      - 3003:3003
    depends_on:
      - mongodb
    links:
      - mongodb

################################
# Databases
################################
  wildzone-database-suppliers:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_ROOT_PASSWORD}
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo
    container_name: Wildzone-database-products
    ports: 
      - 27017:27017
    expose:
      - 27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    restart: always

################################
# Databases Admins
################################  

  wildzone-db-admin-suppliers:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: wildzone-database-suppliers
    depends_on:
      - wildzone-database-suppliers


################################
# Volumes
################################  
volumes:
  data: {}
    